### ISSUE TITLE
rflink unter Node.js 12.18 kein Com Port

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.rflink#30]
Hallo, ich habe seit dem Update auf Nodejs12.18 keine Möglichkeit einen COM Port auszuwählen.
Betriebssystem ist Windows.

Siehe iobroker Forum -> https://forum.iobroker.net/topic/34318/rflink-nodejs12-18

**Comment by Apollon77** [comment]
Npm rebuild ausgeführt mach dem nodejs as update?
Bzw generell die Anleitung befolgt zu einem node Update und iobroker im Forum?

**Comment by JBSullivan** [comment]
Als Windows User bin ich nach dieser Anleitung für ein node.js update vorgegangen. Da steht nichts von npm rebuild - habe bis heute nichts auch noch nichts von npm rebuild gehört :( 

> ANLEITUNG FÜR WIN x64 SYSTEME:

1) Node.js:

Datei herunterladen und installieren (aktuell: 12.16.3 LTS): https://nodejs.org/dist/v12.16.3/node-v12.16.3-x64.msi
Einstellungen für die Installation:
generell einfach die Standardeinstellungen verwenden (und Rückfragen der Windows Benutzerkontensteuerung bestätigen), bis auf folgende...
Ausnahme: Häkchen bei "automatically install all necessary tools" setzen!
Die folgende Fehlermeldung (relativ zu Beginn) kann ignoriert werden: "WARNUNG: Not setting tab completion: Profile file does not exist at 'C:\Users[Name des Benutzers]\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'".
Neustart nach Abschluß aller Installationsprozesse.

Also mit anderen Worten NEIN, kein npm rebuild gemacht. Ich habe es  aber auf meinem Testsystem anderweitig zum laufen bekommen (siehe Link oben). Auf meinem zweiten Testsystem werde ich es aber "ordnungsgemäß" machen mit:

C://iobroker/GLT/node_modules/serialport
npm install --production

.... muss danach dann trotzdem noch "npm rebuild" laufen?

**Comment by Apollon77** [comment]
Ne danach reicht ohnw
