### ISSUE TITLE
rflink.0 info List of port: []

### ISSUE THREAD

**Issue by w00dst0ck** [ioBroker/ioBroker.rflink#37]
I've updatest the raspbian system and now I can't select a Serialport for rflink.
The log shows the following messages:

Source | Date | Level | Message
-- | -- | -- | --
rflink.0 | 2021-01-11 11:44:16.345 | info | (17376) List of port: []
rflink.0 | 2021-01-11 11:44:15.056 | info | (17376) List of port: []
rflink.0 | 2021-01-11 11:44:11.826 | info | (17376) Serial port opened
rflink.0 | 2021-01-11 11:44:11.712 | info | (17376) starting. Version 2.1.6 in /opt/iobroker/node_modules/iobroker.rflink, node: v12.20.1, js-controller: 3.1.6

$uname -a
Linux pi4 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

Any idea, how to fix this?

**Comment by Apollon77** [comment]
Is the USB device listes if you look on the system itself?
ALso try "Iobroker fix" to adjust pot needed permissions

**Comment by w00dst0ck** [comment]
Sorry for the delay of my answer.

The problem still exists...

If I replug the device it`s recognized and dmesg shows the following.

```
[9159589.569506] ch341-uart ttyUSB1: ch341-uart converter now disconnected from ttyUSB1
[9159589.569585] ch341 1-1.1:1.0: device disconnected
[9159594.216236] usb 1-1.1: new full-speed USB device number 6 using xhci_hcd
[9159594.352493] usb 1-1.1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.54
[9159594.352502] usb 1-1.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[9159594.352509] usb 1-1.1: Product: USB2.0-Serial
[9159594.358615] ch341 1-1.1:1.0: ch341-uart converter detected
[9159594.362583] usb 1-1.1: ch341-uart converter now attached to ttyUSB1
```

**Comment by Apollon77** [comment]
Ok,After that replug and opening admin page again it should load it

**Comment by w00dst0ck** [comment]
![image](https://user-images.githubusercontent.com/1853382/116303788-535bd580-a7a2-11eb-91cb-1206986f51c2.jpeg)

![image](https://user-images.githubusercontent.com/1853382/116304172-8f8f3600-a7a2-11eb-9c2c-33a6e4fba49a.jpeg)

😕

**Comment by Apollon77** [comment]
Und es gibt das /dev/ttyUSB1 wirklich?

**Comment by w00dst0ck** [comment]
Das Device gibt es und der User, unter dem iobroker läuft, ist auch Mitglied der Gruppe dialout.

```
pi@pi4:~ $ ls -l /dev |grep USB
crw-rw---- 1 root dialout 188,   0 Jan 11 13:36 ttyUSB0
crw-rw---- 1 root dialout 188,   1 Apr 27 23:32 ttyUSB1
```

```
pi@pi4:~ $ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi iobroker
```

**Comment by Apollon77** [comment]
does it change when you execute "iobroker fix"?

**Comment by Apollon77** [comment]
PS: User iobroker is relevant, not root and not "pi" :-)

**Comment by w00dst0ck** [comment]
> PS: User iobroker is relevant, not root and not "pi" :-)

Makes sense. 👍 

But the user iobroker is also member of the right group.

```
$ groups iobroker
iobroker : iobroker tty dialout audio video bluetooth i2c gpio
```

iobroker fix results into this message

```
 $ iobroker fix
iobroker fix

Execute the installation fixer script, this updates your ioBroker installation

Options:
      --help     Show help  [boolean]
  -v, --version  Show version  [boolean]
```

Running the **fix_installation.sh** won't help.

**Comment by w00dst0ck** [comment]
I've tried some things and 
```
npm audit fix --force
```
seems to be the thing who fixed my issue.

**Comment by Apollon77** [comment]
And what exactly did it updated? Thats indeed ervy strange and this command is very risky!
