### ISSUE TITLE
BrelMotor Stop Command

### ISSUE THREAD

**Issue by bjwelker** [ioBroker/ioBroker.rflink#4]
Derzeit gehen bei den Brel Motoren UP und DOWN. Würde man es auch hinbekommen dort den STOP Command einzubauen damit man das hoch oder runterfahren anhalten kann ?

**Comment by GermanBluefox** [comment]
Ich kann ein x-beliebiges Kommando nicht einbauen. Wenn rflink Firmware das unterstützt,  dann kann ich natürlich es implementieren.
Hier kann man finden die Kommandoliste: http://www.nemcon.nl/blog2/protref

Wenn Kommando nicht da ist, dann muss man das Kommando aufzeichnen und an rflink fw Entwickler schicken.  Wie man ein Kommando aufzeichnet,  weiß ich nicht, aber maxtox im Forum sollte es wissen

**Comment by bjwelker** [comment]
Das wird ja unterstützt.
20;07;BrelMotor;ID=xxxxxx;SWITCH=xxxxxx;CMD=UP;
20;07;BrelMotor;ID=xxxxxx;SWITCH=xxxxxxx;CMD=DOWN;
20;07;BrelMotor;ID=xxxxxxx;SWITCH=xxxxxx;CMD=STOP;

**Comment by GermanBluefox** [comment]
Bitte die version vom git testen

**Comment by bjwelker** [comment]
Muss ich die Geräte neu einlernen?

**Comment by GermanBluefox** [comment]
Ich vermute nur BrelMotor.

2017-02-04 0:15 GMT+01:00 Bjoern <notifications@github.com>:

**Comment by bjwelker** [comment]
so probiert. es wird beim einlernen ein bild state und blind stop button pro kanal erzeugt sieht gut aus. ich schätze mal hoch runter mache ich über state true/false?

**Comment by GermanBluefox** [comment]
Ja. Genauso wie früher.

**Comment by bjwelker** [comment]
Scheint gut zu laufen hab es heute im Script benutzt mal sehen was die Tage so bringen. Kannst erst einmal zu machen
