### ISSUE TITLE
Kompatibilität RFLink Nodejs 16.16

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.rflink#41]
Seit der Installation von Nodejs 16.16.0 + nmp 8.11.0, startet RFlink in der Version 2.1.6 mit folgendem Hinweis (siehe unten) nicht  mehr.

Nach der Aktualisierung von Nodejs wurde ein `npm install serialport --build-from-source` ausgeführt, was aber keinen Erfolg brachte.

`<html>
<body>

host.GLTGLT) |   | 2022-07-16 10:25:04.568 | error | host.GLT(GLT) instance system.adapter.rflink.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | -- | --
host.GLTGLT) |   | 2022-07-16 10:25:04.568 | error | host.GLT(GLT) Caught by controller[1]: at node:internal/main/run_main_module:17:47
host.GLTGLT) |   | 2022-07-16 10:25:04.568 | error | host.GLT(GLT) Caught by controller[1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
host.GLTGLT) |   | 2022-07-16 10:25:04.568 | error | host.GLT(GLT) Caught by controller[1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: at Object.<anonymous> (C:\iobroker\GLT\node_modules\iobroker.rflink\main.js:17:17)
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'supportsFeature')
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]:
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: ^
host.GLTGLT) |   | 2022-07-16 10:25:04.567 | error | host.GLT(GLT) Caught by controller[1]: if (adapter.supportsFeature && !adapter.supportsFeature('CONTROLLER_NPM_AUTO_REBUILD')) {
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[1]: C:\iobroker\GLT\node_modules\iobroker.rflink\main.js:17
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\lib\binding\node-v93-win32-ia32\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\compiled\16.16.0\win32\ia32\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.566 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\build\default\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\Release\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\out\Release\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\Debug\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\out\Debug\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\build\Release\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.565 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\build\Debug\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.564 | error | host.GLT(GLT) Caught by controller[0]: → C:\iobroker\GLT\node_modules\@serialport\bindings\build\bindings.node
host.GLTGLT) |   | 2022-07-16 10:25:04.564 | error | host.GLT(GLT) Caught by controller[0]: Cannot load serialport module : Error: Could not locate the bindings file. Tried:
host.GLTGLT) |   | 2022-07-16 10:25:00.545 | error | host.GLT(GLT) iobroker npm-rebuild: Rebuilding native modules failed
host.GLTGLT) |   | 2022-07-16 10:24:01.740 | error | host.GLT(GLT) instance system.adapter.rflink.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.GLTGLT) |   | 2022-07-16 10:24:01.739 | error | host.GLT(GLT) Caught by controller[1]: at node:internal/main/run_main_module:17:47
host.GLTGLT) |   | 2022-07-16 10:24:01.739 | error | host.GLT(GLT) Caught by controller[1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.GLTGLT) |   | 2022-07-16 10:24:01.740 | warn | host.GLT(GLT) adapter "rflink" seems to be installed for a different version of Node.js. Trying to rebuild it... 3 attempt

</body>
</html>`

**Comment by Apollon77** [comment]
Also ein npm imnstall serialsport ist schonmal blödsinn weil du damit ggf eine neuere und inkompatible Serialport version bekommst ... 
ALso erstmal das fiixen und am besten Adappter hier löschen und neu installieren.

Der Richtige weg falls danach eine ähnliche Meldung kommt ist ein

`
cd C:\iobroker\GLT\node_modules\@serialport\bindings
npm install
`

Dann schauen.
