### ISSUE TITLE
Windrichtung Wetterstation falsch

### ISSUE THREAD

**Issue by Matzebhv** [ioBroker/ioBroker.rflink#6]
Moin,

nachdem ich meine Sensoren getauscht habe funktioniert die Erkennung durch RFLink jetzt einwandfrei.
Allerdings werden die Werte für die Windrichtung falsch interpretiert.

Ein
20;96;DKW2012;ID=00ab;TEMP=0073;HUM=90;WINSP=007a;WINGS=00dc;RAIN=005d;WINDIR=0012;BAT=OK;

Ergibt laut RFLink 80Grad. Es wird hier die Richtung angezeigt, in die der Wind weht und nicht die Richtung aus der er weht. Sensor steht richtig, Norden sind WINDIR=0 was auch mit 0 Grad richtig gerechnet wird.
Matze

**Comment by Matzebhv** [comment]
Moin,

da hier noch kein Feedback ist.

Die Windrichtung wird ja durch:

WINDIR: function(value) {

        return Math.round(parseInt(value) * 10000 / 15) / 100;

berechnet.
Die mir bekannten Sensoren senden die Werte von 0-15 für die Windrichtung. Will heißen, wir haben hier eine Auflösung von 22,5 Grad.
Damit wäre dann doch:

return Math(parseInt(value) * 22,5;

die Richtige Berechnung, oder? Lag bei der Entwicklung ein anderer Sensor vor?
Und warum wird im Quellcode hier erst mit 10000 multipliziert und am ende durch 100 dividert?
Bin kein Programmierer, vielleicht sehe ich die Idee dahinter einfach nicht :-)

Gruß
Matze

**Comment by Apollon77** [comment]
Fixed by 1.1.6

**Comment by Matzebhv** [comment]
Vielen Dank Ingo !!
